version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: prisma-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - prisma-network
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data:

networks:
  prisma-network:
    driver: bridge
