version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: guatemaladotcom-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
      # Montar el dump SQL para inicialización
      - ${SQL_DUMP_PATH}:/docker-entrypoint-initdb.d/aprende_db.sql:ro
    networks:
      - guatemaladotcom-network
    command: --default-authentication-plugin=mysql_native_password --max_allowed_packet=1073741824



volumes:
  mysql_data:

networks:
  guatemaladotcom-network:
    driver: bridge
