service: learn-headless-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  architecture: arm64
  region: us-east-1
  memorySize: 2048
  timeout: 10
  environment:
    NODE_ENV: dev

functions:
  main:
    handler: src/handler.main
    events:
      - httpApi:
          path: /
          method: GET

plugins:
  - serverless-jetpack
  - serverless-offline 