name: Deploy Lambda

on:
  push:
    branches: [feature/github-actions]
      #- main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-2
      FUNCTION_NAME: aprende_headless_api

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build with esbuild
        run: |
          pnpm add -D esbuild
          npx esbuild src/handler.ts --bundle --platform=node --target=node20 --outfile=dist/index.js \
            --external:@nestjs/websockets \
            --external:@nestjs/microservices \
            --external:@codegenie/serverless-express

      - name: Zip Lambda
        run: |
          mkdir -p bundle
          cp dist/index.js bundle/index.js
          cd bundle
          zip -r ../lambda.zip .

      - name: Deploy to AWS Lambda
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          inline-script: |
            aws lambda update-function-code \
              --function-name ${{ env.FUNCTION_NAME }} \
              --zip-file fileb://lambda.zip


