name: Deploy Lambda

on:
  push:
    branches: [feature/github-actions]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-west-2
      FUNCTION_NAME: aprende_headless_api

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.11.0

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate Prisma client
        run: pnpm generate

      - name: Install esbuild
        run: pnpm add -D esbuild

      - name: Build with esbuild
        run: |
          npx esbuild src/handler.ts --bundle --platform=node --target=node20 --outfile=dist/index.js \
            --external:@nestjs/websockets \
            --external:@nestjs/microservices \
            --external:@codegenie/serverless-express

      - name: Create Lambda zip
        run: |
          mkdir -p bundle
          cp dist/index.js bundle/index.js
          cd bundle
          zip -r ../lambda.zip .

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name ${{ env.FUNCTION_NAME }} \
            --zip-file fileb://lambda.zip
